#!/usr/bin/env python

from sat_track import *

robot = config.get_robot()
robot.update(0,0)

print("Rotate Azimuth 0 elevation")
for i in range(0,360):
    robot.update(i,0)
    sleep(0.05)
        
print("Rotate Azimuth 30 elevation")
for i in range(0,360):
    robot.update(i,30)
    sleep(0.05)
        
print("Rotate Azimuth Reverse 80 elevation")
for i in range(0,360):
    robot.update(360-i,80)
    sleep(0.05)
        
