#!/usr/bin/env python

from sat_track import *
import sys

home = Home("EN90xj")

directory = todays_directory()

if len(sys.argv) > 1:
        
    satellites = sys.argv[1:]
        
else:
    print("No satellite provided. Deafulting to NOAA 15")
    satellites = ["NOAA 15 [B]"]

directory.list_next_passes(home, satellites)
