#!/usr/bin/env python

from sat_track import *

def calibration_check():
    print("Calibration Check, 0/0")
    servo1.set_angle(0)
    servo2.set_angle(0)

    sleep(5)

    print("Rotating 180")

    servo1.set_angle(180)
    sleep(5)

    print("Elevating 180")
    servo2.set_angle(180)
    sleep(5)

def rotation_test(minutes):
    substeps = 1000
    sleep_time = (60.0 * minutes) / substeps

    print(sleep_time)


    print("Rotation test... %d minute forward" % minutes)

    for i in range(substeps+1):
        angle = 180.0 * i / substeps
#        print(angle)
        servo1.set_angle(angle)
        servo2.set_angle(angle)
        sleep(sleep_time)
        
    print("Rotation test... %d minute reverse" % minutes)
    for i in range(substeps+1):
        angle = 180.0 - (180.0 * i / substeps)
#        print(angle)
        servo1.set_angle(angle)
        servo2.set_angle(angle)
        sleep(sleep_time)




servo1 = Servo(4)
servo2 = Servo(22, max=2350)

calibration_check()
    
