#!/usr/bin/env python

from sat_track import *

home = Home("EN90xj")
robot = AntennaRobot(4,22, elevation_max=2350, elevation_min=610)
tracker = Tracker(robot, home)

    
tracker.track(sys.argv[1])
